### ISSUE TITLE
Speed FPS

### ISSUE THREAD

**Issue by uchiha27** [robot-learning-freiburg/PanopticBEV#1]
What is the speed of the model? Does it work in real-time?

**Comment by nikhilgosala** [comment]
Hi,

Our network has an average runtime of _277.5 ms_ for the KITTI-360 dataset and _238.7 ms_ for the nuScenes dataset. You can find more information about the runtimes in the _Experimental Evaluation_ section of our [paper](https://arxiv.org/pdf/2108.03227.pdf).

**Comment by Lyric0620** [comment]
@nikhilgosala do you remember which gpu did you use for experimence
