### ISSUE TITLE
'list' object has no attribute 'cuda'

### ISSUE THREAD

**Issue by sborse3** [robot-learning-freiburg/PanopticBEV#14]
Hi,
Have you seen this error before? I tried training from scratch and get this for:

for it, sample in enumerate(dataloader):
    sample = {k: sample[k].cuda(device=varargs['device'], non_blocking=True) for k in NETWORK_INPUTS}

Thanks,
Shubhankar

**Comment by nikhilgosala** [comment]
Hey!
This usually happens when the input data format has been tweaked, or some files are not being loaded in the correct data format. As a temporary solution, you can tweak the `iss_collate_fn()` to to suit your needs, or manually apply `.cuda()` to all the entries in the list.
