### ISSUE TITLE
Support multi-camera input?

### ISSUE THREAD

**Issue by lygbuaa** [robot-learning-freiburg/PanopticBEV#2]
Really great work! A little question, I saw the **teaser.png** (https://github.com/robot-learning-freiburg/PanopticBEV/blob/master/images/teaser.png) was generated from 6 cameras (should be nuscenes dataset?), but in nuscenes.ini, only listed cam_front.
`[cameras]
intrinsics = {"fx": 1266.4172, "fy": 51276.4172, "px": 816.267, "py": 491.507}
extrinsics = {"translation": (0.0, 0.6, 1.85), "rotation": (-90, 0, 180)}
bev_params = {"f": 336, "cam_z": 26}`

**So how can I enable multi-camera input for PanopticBEV?  Or can you post a multi-camera version?**

**Comment by nikhilgosala** [comment]
Hi, Thank you for your interest in our project. 

At the moment, the code only supports a single RGB image as input, and we do not plan on releasing the multi-camera version.
However, you can easily extend our approach to multiple cameras by changing the dataloader to load all the 6 images, predicting the masks for each RGB image independently, and then merging the predictions using the known camera extrinsics. 

You can find all the relevant information pertaining to the camera intrinsics and extrinsics in the official nuScenes repository.

**Comment by lygbuaa** [comment]
> 

Thanks for reply, I think it make sense, worth a shot.

**Comment by tuanho27** [comment]
Hi @nikhilgosala,

So could you also release the script to merge multi-views after getting each view result as your paper report? 

Thanks

**Comment by nikhilgosala** [comment]
As mentioned above, we do not plan on releasing any code pertaining to the multi-camera version.
