### ISSUE TITLE
Where is the dataset annotation tool mentioned in the paper supplementary?

### ISSUE THREAD

**Issue by lygbuaa** [robot-learning-freiburg/PanopticBEV#4]
I downloaded nuscenes_panopticbev.zip, and found only front camera ground truth, but I need labels for all 6 cameras, so can you release the dataset annotation tool?  Or the whole annotated nuscenes for 6 cameras, that will be helpful.

**Comment by nikhilgosala** [comment]
Hi,
We unfortunately cannot provide the labels for all 6 cameras in the paper. All our experiments are based on the front camera and we have provided the same in the KITTI360 PanopticBEV and nuScenes PanopticBEV datasets.
